const Products: any = [
  {
    name: "Milk Storage Tank",
    image: "/Images/Dairy1.png",
    rating: 4.5,
    price: 2000,
    availability: "In Stock",
  },
  {
    name: "Milking Machine ",
    image: "/Images/Dairy2.png",
    rating: 4.5,
    price: 6000,
    availability: "In Stock",
  },
  {
    name: "Dairy Pasteurizer",
    image: "/Images/Dairy3.png",
    rating: 4.5,
    price: 5000,
    availability: "In Stock",
  },
  {
    name: "Milk Cooling Syste",
    image: "/Images/Dairy4.png",
    rating: 4.5,
    price: 4000,
    availability: "In Stock",
  },
  {
    name: "Cheese Aging Rack    ",
    image: "/Images/Dairy5.png",
    rating: 4500,
    price: 3.63,
    availability: "In Stock",
  },
  {
    name: "Dairy Homogenizer",
    image: "/Images/Dairy20.png",
    rating: 4.5,
    price: 6050,
    availability: "In Stock",
  },
  {
    name: "Cheese Vat",
    image: "/Images/Dairy7.png",
    rating: 4.5,
    price: 6500,
    availability: "In Stock",
  },
  {
    name: "Cheese Vat",
    image: "/Images/Dairy8.png",
    rating: 4.5,
    price: 6500,
    availability: "In Stock",
  },
  {
    name: "Dairy Pasteurizer",
    image: "/Images/Dairy9.png",
    rating: 4.5,
    price: 3000,
    availability: "In Stock",
  },
  {
    name: "Dairy Homogenizer",
    image: "/Images/Dairy10.png",
    rating: 4.5,
    price: 7500,
    availability: "In Stock",
  },
  {
    name: "Milk Storage Tank",
    image: "/Images/Dairy11.png",
    rating: 4.5,
    price: 6.5,
    availability: "In Stock",
  },
  {
    name: "Cheese Vat",
    image: "/Images/Dairy12.png",
    rating: 4.5,
    price: 6030,
    availability: "In Stock",
  },
  {
    name: "Milk Storage Tank",
    image: "/Images/Dairy17.png",
    rating: 4.5,
    price: 6030,
    availability: "In Stock",
  },
  {
    name: "Dairy Pasteurizer",
    image: "/Images/Dairy14.png",
    rating: 4.5,
    price: 6030,
    availability: "In Stock",
  },
  {
    name: "Plow",
    image: "/Images/Dairy15.png",
    rating: 4.5,
    price: 6030,
    availability: "In Stock",
  },
  {
    name: "Tractor    ",
    image: "/Images/Dairy16.png",
    rating: 4.5,
    price: 6030,
    availability: "In Stock",
  },
  {
    name: "Plow",
    image: "/Images/Dairy17.png",
    rating: 4.5,
    price: 6030,
    availability: "In Stock",
  },
  {
    name: "Harrow",
    image: "/Images/Dairy20.png",
    rating: 4.5,
    price: 6030,
    availability: "In Stock",
  },

  {
    name: "Cultivator",
    image: "/Images/Farm1.png",
    rating: 4.5,
    price: 2000,
    availability: "In Stock",
  },
  {
    name: "Combine Harvester",
    image: "/Images/Farm2.png",
    rating: 4.5,
    price: 6000,
    availability: "In Stock",
  },
  {
    name: "Irrigation System",
    image: "/Images/Farm3.png",
    rating: 4.5,
    price: 5000,
    availability: "In Stock",
  },

  {
    name: "Handoperator",
    image: "/Images/Handoperator.png",
    rating: 4.5,
    price: 4000,
    availability: "In Stock",
  },
  {
    name: "Fertilizer Spreader",
    image: "/Images/Farm5.png",
    rating: 4500,
    price: 3.63,
    availability: "In Stock",
  },
  {
    name: "Fertilizer Spreader",
    image: "/Images/Farm6.png",
    rating: 4.5,
    price: 6050,
    availability: "In Stock",
  },
  {
    name: "Hay Baler",
    image: "/Images/Farm7.png",
    rating: 4.5,
    price: 6500,
    availability: "In Stock",
  },
  {
    name: "Fertilizer Spreader",
    image: "/Images/Farm8.png",
    rating: 4.5,
    price: 6500,
    availability: "In Stock",
  },
  {
    name: "Harrow",
    image: "/Images/Farm9.png",
    rating: 4.5,
    price: 3000,
    availability: "In Stock",
  },
  {
    name: "Harrow",
    image: "/Images/Farm10.png",
    rating: 4.5,
    price: 7500,
    availability: "In Stock",
  },
  {
    name: "Harrow",
    image: "/Images/Farm11.png",
    rating: 4.5,
    price: 6.5,
    availability: "In Stock",
  },
  {
    name: "Harrow",
    image: "/Images/Farm12.png",
    rating: 4.5,
    price: 6030,
    availability: "In Stock",
  },
  {
    name: "Harrow",
    image: "/Images/Poult1.png",
    rating: 4.5,
    price: 6030,
    availability: "In Stock",
  },
  {
    name: "Harrow",
    image: "/Images/Poult2.png",
    rating: 4.5,
    price: 6030,
    availability: "In Stock",
  },
  {
    name: "Harrow",
    image: "/Images/Poult3.png",
    rating: 4.5,
    price: 6030,
    availability: "In Stock",
  },
  {
    name: "Harrow",
    image: "/Images/Poult4.png",
    rating: 4.5,
    price: 6030,
    availability: "In Stock",
  },
  {
    name: "Harrow",
    image: "/Images/poult5.png",
    rating: 4.5,
    price: 6030,
    availability: "In Stock",
  },
  {
    name: "NHarrow",
    image: "/Images/poult6.png",
    rating: 4.5,
    price: 6030,
    availability: "In Stock",
  },

  {
    name: "Harrow",
    image: "/Images/Poult7.png",
    rating: 4.5,
    price: 2000,
    availability: "In Stock",
  },
  {
    name: "Harrow",
    image: "/Images/Poult8.jpeg",
    rating: 4.5,
    price: 6000,
    availability: "In Stock",
  },
  {
    name: "CHarrow",
    image: "/Images/Poult9.png",
    rating: 4.5,
    price: 5000,
    availability: "In Stock",
  },
  {
    name: "Harrow",
    image: "/Images/Poult10.png",
    rating: 4.5,
    price: 4000,
    availability: "In Stock",
  },
  {
    name: "Ventilation System",
    image: "/Images/poult11.png",
    rating: 4500,
    price: 3.63,
    availability: "In Stock",
  },
  {
    name: "Ventilation System",
    image: "/Images/poult12.png",
    rating: 4.5,
    price: 6050,
    availability: "In Stock",
  },
  {
    name: "Brooder",
    image: "/Images/Poult13.png",
    rating: 4.5,
    price: 6500,
    availability: "In Stock",
  },
  {
    name: "Tunk Ramen",
    image: "/Images/tunky14.png",
    rating: 4.5,
    price: 6500,
    availability: "In Stock",
  },
  {
    name: "Noddle's Ramen",
    image: "/Images/Poult15.png",
    rating: 4.5,
    price: 3000,
    availability: "In Stock",
  },
  {
    name: "Egg Grading Machine",
    image: "/Images/Dairy10.png",
    rating: 4.5,
    price: 7500,
    availability: "In Stock",
  },
  {
    name: "ventilation System",
    image: "/Images/Dairy11.png",
    rating: 6.5,
    price: 6.5,
    availability: "In Stock",
  },
  {
    name: "Poultry Scales",
    image: "/Images/Dairy12.png",
    rating: 4.5,
    price: 6030,
    availability: "In Stock",
  },
  {
    name: "Nesting Boxes",
    image: "/Images/Dairy13.png",
    rating: 3.8,
    price: 6030,
    availability: "In Stock",
  },
  {
    name: "Egg Candler  ",
    image: "/Images/Dairy14.png",
    rating: 4.5,
    price: 6030,
    availability: "In Stock",
  },
  {
    name: "Brooder",
    image: "/Images/Dairy15.png",
    rating: 4.5,
    price: 6030,
    availability: "In Stock",
  },
  {
    name: "NIncubator",
    image: "/Images/Dairy16.png",
    rating: 4.5,
    price: 6030,
    availability: "In Stock",
  },
  {
    name: "Automatic Feeder",
    image: "/Images/hatching.jpeg",
    rating: 4.5,
    price: 6030,
    availability: "In Stock",
  },

  {
    name: "Watering System",
    image: "/Images/Boulitto.jpeg",
    rating: 4.5,
    price: 6030,
    availability: "In Stock",
  },
];
export default Products;
